// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"PY_BiaoTiBeiJing","status":false,"description":"(v1.0)更改标题背景","parameters":{"标题背景":"beijing","动态背景":"","菜单背景":"","动态图片横纵向是否开启":"1","动态背景横向移动速度":"1","动态背景纵向移动速度":"1","动态背景透明度":"100"}},
{"name":"TitleVideo","status":true,"description":"视频标题插件","parameters":{"Video Name":"TitleMovie","Muted":"no","Volume":"1","Width":"auto","Height":"auto","X":"0","Y":"0","Loop":"yes","Playback Rate":"1.0","Blend Mode":"NORMAL","Opacity":"1.0","Tint":"0xffffff","Loop Start":"0","Loop End":"end","Debug":"no"}}
];
